on: push
name: Jira Issue Creation Demo
jobs:
  jiraIssueCreation:
    name: Jira Issue Creation Demo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Jira Creation Demo
        uses: bryan-nice/jira-issue-creation@master
        env:
          JIRA_API_TOKEN: 'jiraApiToke'
          JIRA_USERNAME: 'user@email.com'
          JIRA_ACCOUNT_URL: 'https://someaccount.atlassian.net/'
          JIRA_PROJECT: 'jira-issue-creation'
          JIRA_ISSUE_TYPE: 'Demo''ing Jira Issue Creation'
          JIRA_ISSUE_DESCRIPTION: 'Demo''ing Jira Issue Creation'
          JIRA_ISSUE_SUMMARY: 'Demo''ing Jira Issue Creation'